[package]
name = "scapegoat"
version = "0.1.0"
authors = ["Tiemoko Ballo"]
edition = "2018"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/tnballo/scapegoat"
repository = "https://github.com/tnballo/scapegoat"
documentation = "https://docs.rs/scapegoat"
keywords = ["scapegoat", "bst", "set", "map", "tree"]
categories = ["algorithms", "data-structures"]
description = "Ordered set and map data structures via an arena-based scapegoat tree (memory-efficient, self-balancing binary search tree)."
include = [
    "**/*.rs",
    "**/*.md",
    "Cargo.toml",
    "LICENSE",
]

[dev-dependencies]
criterion = "0.3.3"
rand = { version = "0.7.3", features = ["small_rng"] }
ruut = "0.6.1"

[lib]
name = "scapegoat"
path = "src/lib.rs"

[[bench]]
name = "bench_set"
harness = false