[package]
name = "scapegoat"
version = "1.0.0"
authors = ["Tiemoko Ballo"]
edition = "2018"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/tnballo/scapegoat"
repository = "https://github.com/tnballo/scapegoat"
documentation = "https://docs.rs/scapegoat"
keywords = ["scapegoat", "bst", "set", "map", "tree"]
categories = ["algorithms", "data-structures"]
description = "Ordered set and map data structures via an arena-based scapegoat tree."
include = [
    "**/*.rs",
    "**/*.md",
    "Cargo.toml",
    "LICENSE",
]

[dependencies]
#smallvec = { version = "1.6", optional = true, features = ["const_generics"] }
tinyvec = { version = "1.1", optional = true }

[dev-dependencies]
criterion = "0.3"
rand = { version = "0.7", features = ["small_rng"] }
ruut = "0.6"

[features]
#no_std = ["smallvec"]
no_std = ["tinyvec"]

[lib]
name = "scapegoat"
path = "src/lib.rs"

[[bench]]
name = "bench_set"
harness = false